var searchData=
[
  ['opannotarget_2982',['OpAnnoTarget',['../structcirct_1_1firrtl_1_1OpAnnoTarget.html',1,'circt::firrtl']]],
  ['opconversionpattern_2983',['OpConversionPattern',['../classOpConversionPattern.html',1,'OpConversionPattern'],['../classmlir_1_1OpConversionPattern.html',1,'mlir::OpConversionPattern&lt; SourceOp &gt;']]],
  ['opconversionpattern_3c_20affineloadop_20_3e_2984',['OpConversionPattern&lt; AffineLoadOp &gt;',['../classmlir_1_1OpConversionPattern.html',1,'mlir']]],
  ['opconversionpattern_3c_20affinestoreop_20_3e_2985',['OpConversionPattern&lt; AffineStoreOp &gt;',['../classmlir_1_1OpConversionPattern.html',1,'mlir']]],
  ['opconversionpattern_3c_20handshake_3a_3afuncop_20_3e_2986',['OpConversionPattern&lt; handshake::FuncOp &gt;',['../classmlir_1_1OpConversionPattern.html',1,'mlir']]],
  ['opconversionpattern_3c_20ifop_20_3e_2987',['OpConversionPattern&lt; IfOp &gt;',['../classmlir_1_1OpConversionPattern.html',1,'mlir']]],
  ['operationpass_2988',['OperationPass',['../classmlir_1_1OperationPass.html',1,'mlir']]],
  ['opfileinfo_2989',['OpFileInfo',['../structcirct_1_1ExportVerilog_1_1OpFileInfo.html',1,'circt::ExportVerilog']]],
  ['opoperand_2990',['OpOperand',['../classcirct_1_1support_1_1OpOperand.html',1,'circt::support']]],
  ['oprewritepattern_2991',['OpRewritePattern',['../structmlir_1_1OpRewritePattern.html',1,'mlir']]],
  ['oprewritepattern_3c_20calyx_3a_3aassignop_20_3e_2992',['OpRewritePattern&lt; calyx::AssignOp &gt;',['../structmlir_1_1OpRewritePattern.html',1,'mlir']]],
  ['oprewritepattern_3c_20calyx_3a_3acombgroupop_20_3e_2993',['OpRewritePattern&lt; calyx::CombGroupOp &gt;',['../structmlir_1_1OpRewritePattern.html',1,'mlir']]],
  ['oprewritepattern_3c_20calyx_3a_3agroupdoneop_20_3e_2994',['OpRewritePattern&lt; calyx::GroupDoneOp &gt;',['../structmlir_1_1OpRewritePattern.html',1,'mlir']]],
  ['oprewritepattern_3c_20calyx_3a_3agroupop_20_3e_2995',['OpRewritePattern&lt; calyx::GroupOp &gt;',['../structmlir_1_1OpRewritePattern.html',1,'mlir']]],
  ['oprewritepattern_3c_20ctrlop_20_3e_2996',['OpRewritePattern&lt; CtrlOp &gt;',['../structmlir_1_1OpRewritePattern.html',1,'mlir']]],
  ['oprewritepattern_3c_20ifop_20_3e_2997',['OpRewritePattern&lt; IfOp &gt;',['../structmlir_1_1OpRewritePattern.html',1,'mlir']]],
  ['oprewritepattern_3c_20mlir_3a_3afuncop_20_3e_2998',['OpRewritePattern&lt; mlir::FuncOp &gt;',['../structmlir_1_1OpRewritePattern.html',1,'mlir']]],
  ['oprewritepattern_3c_20mlir_3a_3amoduleop_20_3e_2999',['OpRewritePattern&lt; mlir::ModuleOp &gt;',['../structmlir_1_1OpRewritePattern.html',1,'mlir']]],
  ['oprewritepattern_3c_20optype_20_3e_3000',['OpRewritePattern&lt; OpType &gt;',['../structmlir_1_1OpRewritePattern.html',1,'mlir']]],
  ['oprewritepattern_3c_20scf_3a_3aexecuteregionop_20_3e_3001',['OpRewritePattern&lt; scf::ExecuteRegionOp &gt;',['../structmlir_1_1OpRewritePattern.html',1,'mlir']]],
  ['orop_3002',['OrOp',['../class__comb__ops__ext_1_1OrOp.html',1,'_comb_ops_ext']]],
  ['owningopref_3003',['OwningOpRef',['../classmlir_1_1OwningOpRef.html',1,'mlir']]]
];
