CIRCT: circt::msft::PlacementDB Class Reference
circt::msft::PlacementDB Class Reference
A data structure to contain both the locations of the primitives on the device and instance assignments to said primitives locations, aka placements.
#include <DeviceDB.h>
Classes
struct PlacedInstance
In addition to an Operation which is the instance at the level being modeled in MLIR, the instance path within the MLIR instance is often necessary as most often the instance is an extern module.
struct WalkOrder
Public Types
enum Direction { NONE = 0, ASC = 1, DESC = 2 }
Contains the order to iterate in each dimension for walkPlacements.
Public Member Functions
PlacementDB (Operation *top)
Create a DB treating 'top' as the root module.
PlacementDB (Operation *top, const PrimitiveDB &seed)
LogicalResult addPlacement (PhysLocationAttr, PlacedInstance)
Assign an instance to a primitive.
LogicalResult addPlacement (PDPhysRegionOp, PlacedInstance)
Assign an operation to a physical region. Return false on failure.
size_t addPlacements (const hw::SymbolCache &globalRefs, FlatSymbolRefAttr rootMod, mlir::Operation *)
Using the operation attributes, add the proper placements to the database.
size_t addDesignPlacements ()
Walk the entire design adding placements root at the top module.
LogicalResult removePlacement (PhysLocationAttr)
Remove the placement at a given location.
LogicalResult movePlacement (PhysLocationAttr, PhysLocationAttr)
Move the placement at a given location to a new location.
Optional< PlacedInstance > getInstanceAt (PhysLocationAttr)
Lookup the instance at a particular location.
PhysLocationAttr getNearestFreeInColumn (PrimitiveType prim, uint64_t column, uint64_t nearestToY)
Find the nearest unoccupied primitive location to 'nearestToY' in 'column'.
void walkPlacements (function_ref< void(PhysLocationAttr, PlacedInstance)>, std::tuple< int64_t, int64_t, int64_t, int64_t > bounds=std::make_tuple(-1, -1, -1, -1), Optional< PrimitiveType > primType={}, Optional< WalkOrder >={})
Walk the placement information in some sort of reasonable order.
void walkRegionPlacements (function_ref< void(PDPhysRegionOp, PlacedInstance)>)
Walk the region placement information.
Private Types
using DimDevType = DenseMap< PrimitiveType, PlacedInstance >
using DimNumMap = DenseMap< size_t, DimDevType >
using DimYMap = DenseMap< size_t, DimNumMap >
using DimXMap = DenseMap< size_t, DimYMap >
using InstanceAndRegion = std::pair< PDPhysRegionOp, PlacedInstance >
using RegionPlacements = SmallVector< InstanceAndRegion >
Private Member Functions
Optional< PlacedInstance * > getLeaf (PhysLocationAttr)
Get the leaf node.
Private Attributes
MLIRContext * ctxt
Operation * top
DimXMap placements
RegionPlacements regionPlacements
bool seeded
Detailed Description
A data structure to contain both the locations of the primitives on the device and instance assignments to said primitives locations, aka placements.
Holds pointers into the IR, which may become invalid as a result of IR transforms. As a result, this class should only be used for analysis and then thrown away. It is permissible to persist it through transformations so long as it is maintained along with the transformations.
Definition at line 64 of file DeviceDB.h.
Member Typedef Documentation
DimDevType
using circt::msft::PlacementDB::DimDevType = DenseMap<PrimitiveType, PlacedInstance> private
Definition at line 134 of file DeviceDB.h.
DimNumMap
using circt::msft::PlacementDB::DimNumMap = DenseMap<size_t, DimDevType> private
Definition at line 135 of file DeviceDB.h.
DimXMap
using circt::msft::PlacementDB::DimXMap = DenseMap<size_t, DimYMap> private
Definition at line 137 of file DeviceDB.h.
DimYMap
using circt::msft::PlacementDB::DimYMap = DenseMap<size_t, DimNumMap> private
Definition at line 136 of file DeviceDB.h.
InstanceAndRegion
using circt::msft::PlacementDB::InstanceAndRegion = std::pair<PDPhysRegionOp, PlacedInstance> private
Definition at line 138 of file DeviceDB.h.
RegionPlacements
using circt::msft::PlacementDB::RegionPlacements = SmallVector<InstanceAndRegion> private
Definition at line 139 of file DeviceDB.h.
Member Enumeration Documentation
Direction
enum circt::msft::PlacementDB::Direction
Contains the order to iterate in each dimension for walkPlacements.
The dimensions are visited with columns first, then rows, then numbers within a cell.
Enumerator
NONE
ASC
DESC
Definition at line 84 of file DeviceDB.h.
Constructor & Destructor Documentation
PlacementDB() [1/2]
PlacementDB::PlacementDB (Operation * top)
Create a DB treating 'top' as the root module.
Definition at line 71 of file DeviceDB.cpp.
PlacementDB() [2/2]
PlacementDB::PlacementDB (Operation * top, const PrimitiveDB & seed)
Definition at line 73 of file DeviceDB.cpp.
References addPlacement(), circt::msft::PrimitiveDB::foreach(), and seeded.
Member Function Documentation
addDesignPlacements()
size_t circt::msft::PlacementDB::addDesignPlacements ()
Walk the entire design adding placements root at the top module.
addPlacement() [1/2]
LogicalResult circt::msft::PlacementDB::addPlacement (PDPhysRegionOp , PlacedInstance)
Assign an operation to a physical region. Return false on failure.
addPlacement() [2/2]
LogicalResult circt::msft::PlacementDB::addPlacement (PhysLocationAttr , PlacedInstance)
Assign an instance to a primitive.
Return false if another instance is already placed at that location.
Referenced by addPlacements(), and PlacementDB().
addPlacements()
size_t PlacementDB::addPlacements (const hw::SymbolCache & globalRefs, FlatSymbolRefAttr rootMod, mlir::Operation * op)
Using the operation attributes, add the proper placements to the database.
Return the number of placements which weren't added due to conflicts.
Definition at line 113 of file DeviceDB.cpp.
References addPlacement(), and circt::hw::SymbolCache::getDefinition().
getInstanceAt()
Optional<PlacedInstance> circt::msft::PlacementDB::getInstanceAt (PhysLocationAttr)
Lookup the instance at a particular location.
getLeaf()
Optional< PlacementDB::PlacedInstance * > PlacementDB::getLeaf (PhysLocationAttr loc) private
Get the leaf node.
Abstract this out to make it easier to change the underlying data structure.
Definition at line 233 of file DeviceDB.cpp.
References placements, and seeded.
getNearestFreeInColumn()
PhysLocationAttr circt::msft::PlacementDB::getNearestFreeInColumn (PrimitiveType prim, uint64_t column, uint64_t nearestToY)
Find the nearest unoccupied primitive location to 'nearestToY' in 'column'.
movePlacement()
LogicalResult circt::msft::PlacementDB::movePlacement (PhysLocationAttr , PhysLocationAttr)
Move the placement at a given location to a new location.
Returns failure if nothing was placed at the previous location or something is already placed at the new location.
removePlacement()
LogicalResult circt::msft::PlacementDB::removePlacement (PhysLocationAttr)
Remove the placement at a given location.
Returns failure if nothing was placed there.
walkPlacements()
void circt::msft::PlacementDB::walkPlacements (function_ref< void(PhysLocationAttr, PlacedInstance)> , std::tuple< int64_t, int64_t, int64_t, int64_t > bounds = std::make_tuple(-1, -1, -1, -1), Optional< PrimitiveType > primType = {}, Optional< WalkOrder > = {})
Walk the placement information in some sort of reasonable order.
Bounds restricts the walk to a rectangle of [xmin, xmax, ymin, ymax] (inclusive), with -1 meaning unbounded.
Referenced by circtMSFTPlacementDBWalkPlacements().
walkRegionPlacements()
void PlacementDB::walkRegionPlacements (function_ref< void(PDPhysRegionOp, PlacedInstance)> callback)
Walk the region placement information.
Definition at line 323 of file DeviceDB.cpp.
References regionPlacements.
Member Data Documentation
ctxt
MLIRContext* circt::msft::PlacementDB::ctxt private
Definition at line 131 of file DeviceDB.h.
Referenced by circt.esi.System::run_passes().
placements
DimXMap circt::msft::PlacementDB::placements private
Definition at line 145 of file DeviceDB.h.
Referenced by getLeaf().
regionPlacements
RegionPlacements circt::msft::PlacementDB::regionPlacements private
Definition at line 146 of file DeviceDB.h.
Referenced by walkRegionPlacements().
seeded
bool circt::msft::PlacementDB::seeded private
Definition at line 147 of file DeviceDB.h.
Referenced by getLeaf(), and PlacementDB().
top
Operation* circt::msft::PlacementDB::top private
Definition at line 132 of file DeviceDB.h.
The documentation for this class was generated from the following files:
include/circt/Dialect/MSFT/DeviceDB.h
lib/Dialect/MSFT/DeviceDB.cpp