CIRCT: FuncOpLowering Class Reference
FuncOpLowering Class Reference
Public Member Functions
FuncOpLowering (handshake::FuncOp f)
LogicalResult addMergeOps (ConversionPatternRewriter &rewriter)
LogicalResult addBranchOps (ConversionPatternRewriter &rewriter)
LogicalResult replaceCallOps (ConversionPatternRewriter &rewriter)
LogicalResult setControlOnlyPath (ConversionPatternRewriter &rewriter)
LogicalResult connectConstantsToControl (ConversionPatternRewriter &rewriter, bool sourceConstants)
LogicalResult loopNetworkRewriting (ConversionPatternRewriter &rewriter)
BlockOps insertMergeOps (BlockValues blockLiveIns, blockArgPairs &mergePairs, ConversionPatternRewriter &rewriter)
Operation * insertMerge (Block *block, Value val, ConversionPatternRewriter &rewriter)
LogicalResult replaceMemoryOps (ConversionPatternRewriter &rewriter, MemRefToMemoryAccessOp &memRefOps)
LogicalResult connectToMemory (ConversionPatternRewriter &rewriter, MemRefToMemoryAccessOp memRefOps, bool lsq)
void setMemOpControlInputs (ConversionPatternRewriter &rewriter, ArrayRef< Operation * > memOps, Operation *memOp, int offset, ArrayRef< int > cntrlInd)
LogicalResult finalize (ConversionPatternRewriter &rewriter, TypeRange argTypes, TypeRange resTypes, mlir::FuncOp origFunc)
template<typename F , typename... TArgs>
LogicalResult runPartialLowering (F &&memberFunc, TArgs &...args)
Value getBlockEntryControl (Block *block) const
void setBlockEntryControl (Block *block, Value v)
Private Attributes
DenseMap< Block *, Value > blockEntryControlMap
handshake::FuncOp f
Detailed Description
Definition at line 172 of file StandardToHandshake.cpp.
Constructor & Destructor Documentation
FuncOpLowering()
FuncOpLowering::FuncOpLowering (handshake::FuncOp f) inline explicit
Definition at line 174 of file StandardToHandshake.cpp.
Member Function Documentation
addBranchOps()
LogicalResult FuncOpLowering::addBranchOps (ConversionPatternRewriter & rewriter)
Definition at line 1079 of file StandardToHandshake.cpp.
References getBranchCount(), getSuccResult(), and isLiveOut().
Referenced by lowerFuncOp().
addMergeOps()
LogicalResult FuncOpLowering::addMergeOps (ConversionPatternRewriter & rewriter)
Definition at line 606 of file StandardToHandshake.cpp.
References livenessAnalysis(), and reconnectMergeOps().
Referenced by lowerFuncOp().
connectConstantsToControl()
LogicalResult FuncOpLowering::connectConstantsToControl (ConversionPatternRewriter & rewriter, bool sourceConstants)
Definition at line 1150 of file StandardToHandshake.cpp.
Referenced by lowerFuncOp().
connectToMemory()
LogicalResult FuncOpLowering::connectToMemory (ConversionPatternRewriter & rewriter, MemRefToMemoryAccessOp memRefOps, bool lsq)
Definition at line 1615 of file StandardToHandshake.cpp.
References addJoinOps(), addLazyForks(), addMemOpForks(), getControlValues(), getResultsToMemory(), removeAllocOps(), removeRedundantSinks(), setJoinControlInputs(), and setLoadDataInputs().
Referenced by lowerFuncOp().
finalize()
LogicalResult FuncOpLowering::finalize (ConversionPatternRewriter & rewriter, TypeRange argTypes, TypeRange resTypes, mlir::FuncOp origFunc)
Definition at line 1807 of file StandardToHandshake.cpp.
References findStartOp().
Referenced by lowerFuncOp().
getBlockEntryControl()
Value FuncOpLowering::getBlockEntryControl (Block * block) const
Definition at line 227 of file StandardToHandshake.cpp.
insertMerge()
Operation * FuncOpLowering::insertMerge (Block * block, Value val, ConversionPatternRewriter & rewriter)
Definition at line 413 of file StandardToHandshake.cpp.
References getBlockPredecessorCount().
insertMergeOps()
BlockOps FuncOpLowering::insertMergeOps (BlockValues blockLiveIns, blockArgPairs & mergePairs, ConversionPatternRewriter & rewriter)
Definition at line 442 of file StandardToHandshake.cpp.
loopNetworkRewriting()
LogicalResult FuncOpLowering::loopNetworkRewriting (ConversionPatternRewriter & rewriter)
Definition at line 745 of file StandardToHandshake.cpp.
References LoopNetworkRewriter::processFunction().
Referenced by lowerFuncOp().
replaceCallOps()
LogicalResult FuncOpLowering::replaceCallOps (ConversionPatternRewriter & rewriter)
An instance is activated whenever control arrives at the basic block of the source callOp.
Definition at line 1783 of file StandardToHandshake.cpp.
Referenced by lowerFuncOp().
replaceMemoryOps()
LogicalResult FuncOpLowering::replaceMemoryOps (ConversionPatternRewriter & rewriter, MemRefToMemoryAccessOp & memRefOps)
Definition at line 1322 of file StandardToHandshake.cpp.
References getOpMemRef(), and isMemoryOp().
Referenced by lowerFuncOp().
runPartialLowering()
template<typename F , typename... TArgs> LogicalResult FuncOpLowering::runPartialLowering (F && memberFunc, TArgs &... args) inline
Definition at line 209 of file StandardToHandshake.cpp.
Referenced by lowerFuncOp().
setBlockEntryControl()
void FuncOpLowering::setBlockEntryControl (Block * block, Value v)
Definition at line 234 of file StandardToHandshake.cpp.
setControlOnlyPath()
LogicalResult FuncOpLowering::setControlOnlyPath (ConversionPatternRewriter & rewriter)
Definition at line 268 of file StandardToHandshake.cpp.
Referenced by lowerFuncOp().
setMemOpControlInputs()
void FuncOpLowering::setMemOpControlInputs (ConversionPatternRewriter & rewriter, ArrayRef< Operation * > memOps, Operation * memOp, int offset, ArrayRef< int > cntrlInd)
Definition at line 1576 of file StandardToHandshake.cpp.
References addValueToOperands().
Member Data Documentation
blockEntryControlMap
DenseMap<Block *, Value> FuncOpLowering::blockEntryControlMap private
Definition at line 223 of file StandardToHandshake.cpp.
f
handshake::FuncOp FuncOpLowering::f private
Definition at line 224 of file StandardToHandshake.cpp.
The documentation for this class was generated from the following file:
lib/Conversion/StandardToHandshake/StandardToHandshake.cpp